# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b025fd702d905e632e6d97060f2fdc704ae10033ab4e244baff1d4e8d0345ba8b8f992d12a2ada4d4dce0583248e10a94a24e4d3ce7159b29aa33e764d5aceb

test:
  secret_key_base: a0774e50568e2b37f985fde8a5711170c0a04ff021b2d1a0f35f784b902298370f44bb424efc54c5dcf247fa5361c83bc8b3b3bcd3ee69b0e68da7e5fffada35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
